<?php

return [
    'blockchain_networks' => [
        'TRC20',
        'ERC20',
        'BEP20 (BSC)',
        'Bitcoin',
        'Ethereum',
        'USDC-ERC20',
        'USDC-TRC20',
    ],

    // Sourced from Sieummo admin withdrawal-methods list.
    'sieummo_withdrawal_methods' => [
        ['name' => 'USDT', 'currency' => 'USDT', 'network' => 'TRC20', 'sort_order' => 0],
        ['name' => 'USDT', 'currency' => 'USDT', 'network' => 'ERC20', 'sort_order' => 1],
        ['name' => 'USDT', 'currency' => 'USDT', 'network' => 'BEP20 (BSC)', 'sort_order' => 2],
        ['name' => 'BTC', 'currency' => 'BTC', 'network' => 'Bitcoin', 'sort_order' => 3],
        ['name' => 'ETH', 'currency' => 'ETH', 'network' => 'Ethereum', 'sort_order' => 4],
        ['name' => 'USDC', 'currency' => 'USDC', 'network' => 'USDC-ERC20', 'sort_order' => 5],
        ['name' => 'USDC', 'currency' => 'USDC', 'network' => 'USDC-TRC20', 'sort_order' => 6],
    ],

    'vietnam_banks' => [
        'Agribank',
        'BIDV',
        'VietinBank',
        'Vietcombank',
        'MB Bank',
        'ACB',
        'Techcombank',
        'VPBank',
        'TPBank',
        'Sacombank',
        'SHB',
        'HDBank',
        'VIB',
        'Eximbank',
        'OCB',
        'SeABank',
        'MSB',
        'LPBank',
        'NCB',
        'Nam A Bank',
        'Viet A Bank',
        'VietBank',
        'Bac A Bank',
        'BaoViet Bank',
        'PVcomBank',
        'KienlongBank',
        'Saigonbank',
        'PGBank',
        'ABBank',
        'Co-opBank',
        'CBBank',
        'OceanBank',
        'GPBank',
        'SCB',
        'Woori Bank Vietnam',
        'Shinhan Bank Vietnam',
        'Public Bank Vietnam',
        'CIMB Bank Vietnam',
        'UOB Vietnam',
        'HSBC Vietnam',
        'Standard Chartered Vietnam',
        'Hong Leong Bank Vietnam',
        'Indovina Bank',
        'ANZ Vietnam',
        'DBS Bank Vietnam',
        'United Overseas Bank Vietnam',
    ],
];

